### ISSUE TITLE
Adicionar palavras em WORDREFERENCE.md

### ISSUE THREAD

**Issue by yanmagale** [ember-brasil/website#65]
Olá a todos.

Estava trabalhando na issue #28 e percebi que existiam algumas palavras técnicas que não estavam no documento de `WORDREFERENCE`.

Decidi então trazer estas palavras para cá e saber a opinião de vocês sobre elas, para posterior atualização no documento:

- `Bugfixes` : Correções de Bug
- `feature flags´ : Sinalização de nova funcionalidade
- `bumping the minor version` : Superar a menor versão

**Comment by aureliosaraiva** [comment]
@yanmagale 

`bugfixes` e `feature flags` não precisam de tradução.

`bumping the minor version` é um pouco mais complicado, a tradução não está boa, não da pra entender.

@danilovaz alguma sugestão?

**Comment by danilovaz** [comment]
@yanmagale @aureliosaraiva 

Bom ponto levantado, os termos técnicos geram sempre essa duvida.

Eu acredito que depende do contexto em si. Em determinadas partes do texto eu vi que faz mais sentido `Correções de bugs` do que `Bugfixes`, por exemplo:
`Bugfixes should not introduce new APIs or break existing APIs, and do not need feature flags.`
Talvez mais claro assim:
`Correções de bugs (Bugfixes) nao deveriam introduzir novas APIs ou quebrar APIs existentes, e nao precisam de features flags (sinalizar que e uma tag de feature).`

Bugfixes da para traduzir para Correções de Bugs. Ja feature flags, realmente e mais chatinho.

Ja`bumping the minor version` no original nao da pra ficar e traduzido ficou um pouco estranho, pesquisando na documentacao do SemVer, e possível ver que eles usam o termo e traduzem para `aumentar a maior versão`: http://semver.org/lang/pt-BR/#se-mesmo-a-menor-mudança-incompatível-com-a-api-pública-requer-aumento-da-versão-maior-não-vou-acabar-na-versão-4200-muito-rapidamente

Pegando o contexto inteiro, ficaria assim:
`They should not be applied to the release or beta branches, since SemVer requires bumping the minor version to introduce new features.`

para:
`Elas nao devem ser aplicadas nas branches de release e beta, uma vez que o SemVer requer o aumento da minor version para introduzir novas features.`

Ps. desculpe a falta de acentuações em alguns lugares, deu ruim aqui no teclado =p

**Comment by yanmagale** [comment]
> `Elas nao devem ser aplicadas nas branches de release e beta, uma vez que o SemVer requer o aumento da minor version para introduzir novas features`

Gostei, vou atualizar meu branch com esta tradução.

Atualizarei o que ja havia feito com estas definições. Acho que estes itens poderiam ir pro `Wordreference.md`

**Comment by aureliosaraiva** [comment]
@yanmagale ok, obrigado!
